const roles = {
'Novato \`\`\`V\`\`\` ⚔️': 0,
'Novato \`\`\`IV\`\`\` ⚔️': 2,
'Novato \`\`\`III\`\`\` ⚔️': 4,
'Novato \`\`\`II\`\`\` ⚔️': 6,
'Novato ⚔️': 8,
'Aprendiz \`\`\`V\`\`\` 💡': 10,
'Aprendiz \`\`\`IV\`\`\` 💡': 12,
'Aprendiz \`\`\`III\`\`\` 💡': 14,
'Aprendiz \`\`\`II\`\`\` 💡': 16,
'Aprendiz 💡': 18,
'Guerrero \`\`\`V\`\`\` 🏹': 20,
'Guerrero \`\`\`IV\`\`\` 🏹': 22,
'Guerrero \`\`\`III\`\`\` 🏹': 24,
'Guerrero \`\`\`II\`\`\` 🏹': 26,
'Guerrero 🏹': 28,
'Cadete \`\`\`V\`\`\` 🎓': 30,
'Cadete \`\`\`IV\`\`\` 🎓': 32,
'Cadete \`\`\`III\`\`\` 🎓': 34,
'Cadete \`\`\`II\`\`\` 🎓': 36,
'Cadete 🎓': 38,
'Maestro \`\`\`V\`\`\` 🪄': 40,
'Maestro \`\`\`IV\`\`\` 🪄': 42,
'Maestro \`\`\`III\`\`\` 🪄': 44,
'Maestro \`\`\`II\`\`\` 🪄': 46,
'Maestro 🪄': 48,
'Maestro Élite \`\`\`V\`\`\` 🧙🏻': 50,
'Maestro Élite \`\`\`IV\`\`\` 🧙🏻': 52,
'Maestro Élite \`\`\`III\`\`\` 🧙🏻': 54,
'Maestro Élite \`\`\`II\`\`\` 🧙🏻': 56,
'Maestro Élite 🧙🏻': 58,
'Gran Maestro \`\`\`V\`\`\` 🧙🏻‍♂️': 60,
'Gran Maestro \`\`\`IV\`\`\` 🧙🏻‍♂️': 62,
'Gran Maestro \`\`\`III\`\`\` 🧙🏻‍♂️': 64,
'Gran Maestro \`\`\`II\`\`\` 🧙🏻‍♂️': 66,
'Gran Maestro 🧙🏻‍♂️': 68,
'Supremo \`\`\`V\`\`\` 🗿': 70,
'Supremo \`\`\`IV\`\`\` 🗿': 72,
'Supremo \`\`\`III\`\`\` 🗿': 74,
'Supremo \`\`\`II\`\`\` 🗿': 76,
'Supremo 🗿': 78,
'Visionario \`\`\`V\`\`\` 🔮': 80,
'Visionario \`\`\`IV\`\`\` 🔮': 82,
'Visionario \`\`\`III\`\`\` 🔮': 84,
'Visionario \`\`\`II\`\`\` 🔮': 86,
'Visionario 🔮': 88,
'Líder Visionario \`\`\`V\`\`\` 👑': 90,
'Líder Visionario \`\`\`IV\`\`\` 👑': 92,
'Líder Visionario \`\`\`III\`\`\` 👑': 94,
'Líder Visionario \`\`\`II\`\`\` 👑': 96,
'Líder Visionario 👑': 98,
'Astral \`\`\`V\`\`\` 🌒': 100,
'Astral \`\`\`IV\`\`\` 🌒': 102,
'Astral \`\`\`III\`\`\` 🌒': 104,
'Astral \`\`\`II\`\`\` 🌒': 106,
'Astral 🌒': 108,
'Legendario \`\`\`V\`\`\` 🪝': 110,
'Legendario \`\`\`IV\`\`\` 🪝': 112,
'Legendario \`\`\`III\`\`\` 🪝': 114,
'Legendario \`\`\`II\`\`\` 🪝': 116,
'Legendario 🪝': 118,
'Divino \`\`\`V\`\`\` 🤍': 120,
'Divino \`\`\`IV\`\`\` 🤍': 122,
'Divino \`\`\`III\`\`\` 🤍': 124,
'Divino \`\`\`II\`\`\` 🤍': 126,
'Divino 🤍': 128,
'Mítico \`\`\`V\`\`\` 🪨': 130,
'Mítico \`\`\`IV\`\`\` 🪨': 132,
'Mítico \`\`\`III\`\`\` 🪨': 134,
'Mítico \`\`\`II\`\`\` 🪨': 136,
'Gloria Mítica 🪨': 138,
'Esmeralda \`\`\`V\`\`\` 💚': 140,
'Esmeralda \`\`\`IV\`\`\` 💚': 145,
'Esmeralda \`\`\`III\`\`\` 💚': 150,
'Esmeralda \`\`\`II\`\`\` 💚': 155,
'Esmeralda \`\`\`I\`\`\` 💚': 160,
'Titán \`\`\`V\`\`\` ⚜️': 165,
'Titán \`\`\`IV\`\`\` ⚜️': 170,
'Titán \`\`\`III\`\`\` ⚜️': 185,
'Titán \`\`\`II\`\`\` ⚜️': 200,
'Titán \`\`\`I\`\`\` ⚜️': 250,
'\`Dragón Rey Estrella\` 🐉👑': 300
}

let handler = m => m
handler.before = async function (m, { conn }) {
        let user = db.data.users[m.sender]
        let level = user.level
        let role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0]
        user.role = role
        return !0

}
export default handler 