const roles = {
'*Novato V* 🍄': 0,
'*Novato IV* 🍄': 2,
'*Novato III* 🍄': 4,
'*Novato II* 🍄': 6,
'*Novato I* 🍄': 8,
'*Estudiante V* 🍹': 10,
'*Estudiante IV* 🍹': 12,
'*Estudiante III* 🍹': 14,
'*Estudiante II* 🍹': 16,
'*Estudiante I* 🍹': 18,
'*Rango Medio V* 🥃': 20,
'*Rango Medio IV* 🥃': 22,
'*Rango Medio III* 🥃': 24,
'*Rango Medio II* 🥃': 26,
'*Rango Medio I* 🥃': 28,
'*Maestro V* ☁️': 30,
'*Maestro IV* ☁️': 32,
'*Maestro III* ☁️': 34,
'*Maestro II* ☁️': 36,
'*Maestro I* ☁️': 38,
'*Experto V* 🪐': 40,
'*Experto IV* 🪐': 42,
'*Experto III* 🪐': 44,
'*Experto II* 🪐': 46,
'*Experto I* 🪐': 48,
'*Genio V* 💧': 50,
'*Genio IV* 💧': 52,
'*Genio III* 💧': 54,
'*Genio II* 💧': 56,
'*Genio I* 💧': 58,
'*Superior V* 🍿': 60,
'*Superior IV* 🍿': 62,
'*Superior III* 🍿': 64,
'*Superior II* 🍿': 66,
'*Superior I* 🍿': 68,
'*Experto del Bot V* 🌐': 70,
'*Experto del Bot IV* 🌐': 72,
'*Experto del Bot III* 🌐': 74,
'*Experto del Bot II* 🌐': 76,
'*Experto del Bot I* 🌐': 78,
'*Pro V* 💰': 80,
'*Pro IV* 💰': 82,
'*Pro III* 💰': 84,
'*Pro II* 💰': 86,
'*Pro I* 💰': 88,
'*Pro Superior V* 🎁': 90,
'*𝗣𝗿𝗼 𝗦𝘂𝗽𝗲𝗿𝗶𝗼𝗿 IV* 🎁': 92,
'*𝗣𝗿𝗼 𝗦𝘂𝗽𝗲𝗿𝗶𝗼𝗿 III* 🎁': 94,
'*𝗣𝗿𝗼 𝗦𝘂𝗽𝗲𝗿𝗶𝗼𝗿 II* 🎁': 96,
'*𝗣𝗿𝗼 𝗦𝘂𝗽𝗲𝗿𝗶𝗼𝗿 I* 🎁': 98,
'*𝗥𝗲𝘆 V* 💻': 100,
'*𝗥𝗲𝘆 IV* 💻': 102,
'*𝗥𝗲𝘆 III* 💻': 104,
'*𝗥𝗲𝘆 II* 💻': 106,
'*𝗥𝗲𝘆 I* 💻': 108,
'*𝗥𝗲𝘆 𝗣𝗿𝗼 V* 🎒': 110,
'*𝗥𝗲𝘆 𝗣𝗿𝗼 IV* 🎒': 112,
'*𝗥𝗲𝘆 𝗣𝗿𝗼 III* 🎒': 114,
'*𝗥𝗲𝘆 𝗣𝗿𝗼 II* 🎒': 116,
'*𝗥𝗲𝘆 𝗣𝗿𝗼 I* 🎒': 118,
'*𝗜𝗻𝘃𝗲𝗻𝘀𝗶𝗯𝗹𝗲 V* 🔔': 120,
'*𝗜𝗻𝘃𝗲𝗻𝘀𝗶𝗯𝗹𝗲 IV* 🔔': 122,
'*𝗜𝗻𝘃𝗲𝗻𝘀𝗶𝗯𝗹𝗲 III* 🔔': 124,
'*𝗜𝗻𝘃𝗲𝗻𝘀𝗶𝗯𝗹𝗲 II* 🔔': 126,
'*𝗜𝗻𝘃𝗲𝗻𝘀𝗶𝗯𝗹𝗲 I* 🔔': 128,
'*𝗥𝗲𝗻𝘁𝗮𝗿𝗼 V* 🌌': 130,
'*𝗥𝗲𝗻𝘁𝗮𝗿𝗼 IV* 🌌': 132,
'*𝗥𝗲𝗻𝘁𝗮𝗿𝗼 III* 🌌': 134,
'*𝗥𝗲𝗻𝘁𝗮𝗿𝗼 II* 🌌': 136,
'*𝗥𝗲𝗻𝘁𝗮𝗿𝗼 I* 🌌': 138,
'*𝗣𝗿𝗲𝗺𝗶𝘂𝗺 V* 🏆': 140,
'*𝗣𝗿𝗲𝗺𝗶𝘂𝗺 IV* 🏆': 145,
'*𝗣𝗿𝗲𝗺𝗶𝘂𝗺 III* 🏆': 150,
'*𝗣𝗿𝗲𝗺𝗶𝘂𝗺 II* 🏆': 155,
'*𝗣𝗿𝗲𝗺𝗶𝘂𝗺 I* 🏆': 160,
'*Rey Dragón Ultra V* 👑': 170,
'*Rey Dragón Ultra IV* 👑': 185,
'*Rey Dragón Ultra III* 👑': 200,
'*Rey Dragón Ultra II* 👑': 250,
'*Rey Dragón Ultra* 👑': 300
}

let handler = m => m
handler.before = async function (m, { conn }) {
        let user = db.data.users[m.sender]
        let level = user.level
        let role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0]
        user.role = role
        return !0

}
export default handler 