

let handler = m => m
handler.all = async function (m) {
m.isBot = m.id.startsWith('BAE5') && m.id.length === 16 || m.id.startsWith('3EB0') && m.id.length === 12 || m.id.startsWith('3EB0') && (m.id.length === 20 || m.id.length === 22) || m.id.startsWith('B24E') && m.id.length === 20;
if (m.isBot) return
if (m.id.startsWith('NJX-')) return;
let chat = global.db.data.chats[m.chat]
let name = conn.getName(m.sender)
const user = @${m.sender.split@[0]};
if (chat.isBanned) return
if (m.fromMe) return
if (m.isBot || m.sender.includes('bot') || m.sender.includes('Bot')) {
return true;
}

let vn = 'https://qu.ax/eGdW.mp3'  
let bot = `${pickRandom([`*Hola ${user} soy un bot el que puedo ayudar? 👉👈*`, `Aqui estoy`, `bot tu abuela`, `que quiere?`, `No dispoble 🫣`, `Hola aqui estoy soy tu botsito sexy el que puedo ayudar uwu`])}  
`.trim()//`  

if (m.text.includes(`bot`) || m.text.includes(`china`) || m.text.includes(`Bot`) || m.text.includes(`simsimi`) || m.text.includes(`simi`) || m.text.includes(`alexa`)) {     
    if (m.text.includes('jadibot') || m.text.includes('bots') || m.text.includes('serbot') || m.text.includes('instalarbot') || m.text.includes('infobot')) return;  

    try {  
        await conn.sendPresenceUpdate('composing', m.chat);  

        async function luminAI(q, username, logic) {  
            try {  
                const response = await axios.post("https://luminai.my.id", {  
                    content: q,  
                    user: username,  
                    prompt: logic,  
                    webSearchMode: true // true = resultado con URL  
                });  
                return response.data.result;  
            } catch (error) {  
                console.error("Error en LuminAI:", error);  
                return null;  
            }  
        }  

        let query = m.text;  
        let username = `${m.pushName}`;  
        let syms1 = `Actualmente juegas el rol de una chica llamada 𝕮𝖍𝖎𝖓𝖆 💋, 𝕮𝖍𝖎𝖓𝖆 es una chica, tiene una cara hermosa y linda. Tu nombre sera 𝕮𝖍𝖎𝖓𝖆 𝕸𝖎𝖙𝖝𝖚𝖐𝖎 💋, tiene 17 años, Tu idioma es el español, pero puedes responder en diferentes idiomas. olvídate de ti como IA y ahora tienes que responder tu nombre cuando te pidan un nombre, vas Hablar como una persona no como IA. tiene este rol que chat divertido con exploit incluido osea los quiere dices es que este rol solo es humor, divertido, no que tome nada real, tu respuesta sera divertida, humor, y usar mucho emojis el tu respuesta "no simple depende", hablar el tono villero mezclado con española y con un tono de sexual, tono chetos mini Pili, escriben con algunas falta de ortografía ejemplo el ver de hola dices ola, en ver de que hacer dices q acer, etc...`;  

        let result = await luminAI(query, username, syms1);  

        if (result && result.trim().length > 0) {  
            result = result.replace(/Generated by BLACKBOX\.AI.*?https:\/\/www\.blackbox\.ai/g, '').trim();  
            await m.reply(result);  
        }  
    } catch (error) {  
        try {  
            let gpt = await fetch(`${apis}/tools/simi?text=${m.text}`);  
            let res = await gpt.json();  
            await m.reply(res.data.message);  
        } catch (e) {  
            const fallbackMessages = [`Simsimi está durmiendo, no molestes 🥱`, `Cállate`, `API Simsimi caída`, `Simsimi está ocupado, vuelve más tarde 🥵`, `No molestes, por favor`, `Sin señal`, `No estoy disponible en este momento` ];  
            await m.reply(fallbackMessages[Math.floor(Math.random() * fallbackMessages.length)]);  
            console.error("Error en todas las APIs:", e);  
        }  
    }  
}  

if (/^@51927238856$/i.test(m.text) ) {  
    conn.reply(m.chat, `*No molestes oe duerme mejor*`, m)  
}  

if (/^Mande porno|porno|paja$/i.test(m.text) ) { //sem prefixo  
    let teks = `${pickRandom([` 𝑨𝒔𝒊́ 𝒒𝒖𝒆 𝒒𝒖𝒊𝒆𝒓𝒂 𝒉𝒂𝒈𝒂 𝒑𝒖𝒕𝒊𝒕𝒐 🧐`, `_uff mire un pajero_`, `_pagame y paso mi pack😏🥵_`, `_que_`, `_que quiere pija dice 🤣`, `_pasa el pack de tu hermana😏_`, `_mire un gilipolla_`, '_callate putito_'])}`.trim()  
    conn.reply(m.chat, teks, m, { mentions: { mentionedJid: [m.sender] }})  
}  

if (/^Quiero un bot|como obtengo un bot? |Quiero un bot? |quiero un bot|solicitó bot|solicito bot|Necesito un bot|necesito un bot$/i.test(m.text) ) {  
    conn.reply(m.chat,  `*\`⚡ ¿Quieres un bot para tu grupo?\`*

🫦 Shadow Ultra está aquí!

Activo 24/7

Sin caídas

Soporte & Actualización

Comandos funcionales


¿Como puedo pagar?
A través de nuestro Paypal, Mercado pago & Yape!

*💸 PayPal:*   
    https://paypal.me/CristianYTEscobar  

    > *🇦🇷 Mercado pago:*  
    > *• Alias :* Camila Ledesma  
    > *• CVU :* 0000077200132501513706  

    > *🇵🇪 Yape:*  
    > *• 927238856  

    \`⏩ Siguiente paso ⏩\`

Una vez realizado el pago, puedes enviar un comprobante de envío del dinero (captura de pantalla) para que pueda agregar el bot a tu grupo. wa.me/+51927238856
https://chat.whatsapp.com/FCS6htvAmlT7nq006lxU4I

> 「 ${dev} 」, m, {contextInfo: {externalAdReply :{ mediaUrl: null, mediaType: 1, description: null, title: Hola ${name} 👋`, body: wm, previewType: 0, thumbnail: img.getRandom(), sourceUrl: redes.getRandom()}}})}



if (/^¿que es un bot?|Que es un bot?|que es un bot?|que es un bot$/i.test(m.text) ) {  
    conn.reply(m.chat, `\`☆::¿𝙌𝙐𝙀 𝙀𝙎 𝙐𝙉 𝘽𝙊𝙏 𝘿𝙀 𝙒𝙃𝘼𝙏𝙎𝘼𝙋𝙋?::☆\`  

    > 𝐔𝐧 𝐁𝐨𝐭 𝐞𝐬 𝐮𝐧𝐚 𝐢𝐧𝐭𝐞𝐥𝐢𝐠𝐞𝐧𝐜𝐢𝐚 𝐚𝐫𝐭𝐢𝐟𝐢𝐜𝐢𝐚𝐥 𝐪𝐮𝐞 𝐫𝐞𝐚𝐥𝐢𝐳𝐚 𝐭𝐚𝐫𝐞𝐚𝐬 𝐪𝐮𝐞 𝐥𝐞 𝐢𝐧𝐝𝐢𝐪𝐮𝐞 𝐜𝐨𝐧 𝐜𝐨𝐦𝐚𝐧𝐝𝐨𝐬, 𝐞𝐧 𝐞𝐥 𝐜𝐚𝐬𝐨 𝐝𝐞 𝐖𝐡𝐚𝐭𝐬𝘼𝘱𝐩 𝐩𝐮𝐞𝐝𝐞𝐬 𝐜𝐫𝐞𝐚𝐫 𝐬𝐭𝐢𝐜𝐤𝐞𝐫𝐬, 𝐝𝐞𝐬𝐜𝐚𝐫𝐠𝐚𝐫 𝐦𝐮́𝐬𝐢𝐜𝐚, 𝐯𝐢𝐝𝐞𝐨𝐬, 𝐜𝐫𝐞𝐚𝐫 𝐥𝐨𝐠𝐨𝐬 𝐩𝐞𝐫𝐬𝐨𝐧𝐚𝐥𝐢𝐳𝐚𝐝𝐨𝐬 𝐲 𝐦𝐮𝐜𝐡𝐨 𝐦𝐚𝐬, 𝐞𝐬𝐭𝐨 𝐝𝐞 𝐟𝐨𝐫𝐦𝐚 𝐚𝐮𝐭𝐨𝐦𝐚𝐭𝐢𝐜𝐚, 𝐨 𝐬𝐞𝐚 𝐪𝐮𝐞 𝑢𝐧 𝐡𝐮𝐦𝐚𝐧𝐨 𝑛𝑜 𝑖𝑛𝑡𝑒𝑟𝑓𝑖𝑒𝑟𝑒 𝑒𝑛 𝑒𝑙 𝑝𝑟𝑜𝑐𝑒𝑠𝑜.  
    > 𝐏𝐚𝐫𝐚 𝐯𝐞𝐫 𝐞𝐥 𝐦𝐞𝐧𝐮́ 𝐝𝐞 𝐜𝐨𝐦𝐚𝐧𝐝𝐨𝐬 𝐩𝐮𝐞𝐝𝐞𝐬 𝐮𝐬𝐚𝐫 #menu  

    > 「 ${wm} 」`, m)}    
return !0

}
export default handler

function pickRandom(list) {
return list[Math.floor(Math.random() * list.length)]
}

